### ISSUE TITLE
Concat multiple time steps into single Zarr file

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/metoffice_ec2#20]
As per @tv3141's work in https://github.com/tv3141/metoffice_ec2/blob/storage_optimisation_notebook/storage_optimisation/optimize_storage.ipynb

* reduces data read time
* reduces size on disk by 4%

**Comment by tomwhite** [comment]
We should definitely be doing this so we can read the data back efficiently as a single dataset. I've suggested a way of doing this in #17.

**Comment by JackKelly** [comment]
Oops, sorry, this is a duplicate of #17!  I'll close this for now...
