### ISSUE TITLE
Do we have to use SQS? Can EC2 read directly from SNS?

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/metoffice_ec2#8]

**Comment by JackKelly** [comment]
If our EC2 job stays up 24/7, then I think we could do without SQS.  But I think the SNS endpoint has to be ready to receive the SNS messages as and when they are generated, otherwise they're lost.

Assuming the above is correct: I think we need SQS, which gives us the flexibility to only run the EC2 job once an hour; and also gives us resilience against the EC2 job dying for a little while.

**Comment by flowirtz** [comment]
Also: In case our EC2 consumer goes down, we would loose a bunch of messages.
SQS is nice in that sense, as it would keep the messages for a while, once the consumer recovers it can simple go trough the old messages, without any loss.
